### PR TITLE
Add adapted powershell activations

### LINKED ISSUE #41: Add powershell activation scripts?
### Comment:

Hello!

I'm hoping to use this in https://github.com/conda-forge/cmdstan-feedstock, which is a bit odd in that it actually requires compilers at _run_ time. As such, it would be great if the activation also supported Powershell environments with `[de]activate_*.ps1` scripts

I'm happy to open a PR which adds these, but I wanted to confirm first that it would be likely to be accepted. 

Thanks!

### PR DESCRIPTION
**Pull request by WardBrian**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #41.

The comment in install-pkg.bat about vs activation needing to run first made me realize I'm not sure if https://github.com/conda-forge/vc-feedstock/blob/main/recipe/activate.bat _also_ needs a powershell version for this to work, or if the ordering is just because this sets some of the same variables and therefore needs to run second

### CODE REVIEW

**Comment by h-vetinari** [comment]
> The comment in install-pkg.bat about vs activation needing to run first made me realize I'm not sure if https://github.com/conda-forge/vc-feedstock/blob/main/recipe/activate.bat _also_ needs a powershell version for this to work, or if the ordering is just because this sets some of the same variables and therefore needs to run second

This is a good question that I don't know the answer to, but presumably, if you're in powershell, the `.bat` activation scripts don't get executed, and so you'll need one for vc as well. Can you open a PR that adds powershell activation there to discuss?

Also, please back out the rerender-commit; current conda-build does not rerender this feedstock correctly, and it needs an unreleased version to work (see #42)

**Comment by WardBrian** [comment]
The activation .bat for VC is... quite complicated, but reading through it, seems to be mostly relevant for CMake. They have a couple year old issue for powershell support, but I think it's probably a bit beyond my abilities.  

That said, I've just tried this locally, and it worked for my use case in powershell without any changes to the Visual studio activation.

I've also reverted the rerender. Thanks @h-vetinari

**Comment by WardBrian** [comment]
Gentle ping @h-vetinari

**Comment by h-vetinari** [comment]
I wanted to give the other maintainers here some time to respond, but I guess nothing will break from adding powershell scripts, and if they turn out buggy in some way, we can still fix them later.

**Review by h-vetinari — APPROVED** [review]

**Pull request merged**
